name: CI

on:
  push:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - uses: actions/checkout@v3

    - uses: DeLaGuardo/setup-clojure@10.1
      with:
        cli: '1.11.1.1208'
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: default-build
    - run: clojure -T:build ci
    - uses: codecov/codecov-action@v3
    - name: deploy
      if: github.event.release
      run: clojure -T:build deploy
    