name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: DeLaGuardo/setup-clojure@10.1
      with:
        cli: '1.11.1.1208'
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: default-build
    - run: clojure -T:build ci
    - uses: codecov/codecov-action@v3